kind: project
status:
  state: online
spec:
  functions:
  - url: data_prep.py
    name: load-cancer-data
    kind: job
    image: mlrun/mlrun
  - url: trainer.py
    name: trainer
    kind: job
    image: mlrun/mlrun
    handler: train
  - url: serving.py
    name: serving
    kind: serving
    image: mlrun/mlrun
  desired_state: online
  source: git://github.com/PraneelUJ/CS_203_Lab9#refs/heads/main
  origin_url: git://github.com/PraneelUJ/CS_203_Lab9#refs/heads/main
  conda: ''
metadata:
  created: '2025-04-14T10:39:04.954344'
  name: sttai2-jovyan
